app = "senderlover"  # Nome da aplicação Fly.io para o monorepo
primary_region = "gru"
kill_timeout = 120

# Configuração do backend
[[services]]
  internal_port = 5001  # Porta do backend
  protocol = "tcp"

  [services.build]
    target = "backend"  # Etapa de build do backend

  [[services.ports]]
    handlers = ["http"]
    port = 80  # Porta pública para o backend

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443  # Porta pública para HTTPS

# Configuração do frontend
[[services]]
  internal_port = 80  # Porta para o frontend (Nginx)
  protocol = "tcp"

  [services.build]
    target = "frontend"  # Etapa de build do frontend

  [[services.ports]]
    handlers = ["http"]
    port = 8080  # Porta pública para o frontend

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443  # Porta pública para HTTPS