app = "seu-nome-de-app"

# Configuração geral de build (não duplicada)
[build]
  # Não especificamos aqui o dockerfile, vamos definir cada um nos serviços

[env]
  NODE_ENV = "production"

# Serviço do backend
[[services]]
  internal_port = 5000  # Porta do backend
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80  # Porta pública para o backend

  [services.http_checks]
    interval = 10000
    method = "GET"
    path = "/"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false

  [services.build]
    dockerfile = "./backend/Dockerfile"  # Especifica o Dockerfile do backend

# Serviço do frontend
[[services]]
  internal_port = 80  # Porta do NGINX no frontend
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 8080  # Porta pública para o frontend

  [services.http_checks]
    interval = 10000
    method = "GET"
    path = "/"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false

  [services.build]
    dockerfile = "./frontend/Dockerfile"  # Especifica o Dockerfile do frontend