app = "senderlover"
primary_region = "gru"

# Configuração global de build
[build]
  dockerfile = "./Dockerfile"

# Configuração do backend
[[services]]
  internal_port = 5001  # Porta interna do backend
  protocol = "tcp"
  [services.build]
    target = "backend"  # Target para o backend no Dockerfile

# Configuração do frontend
[[services]]
  internal_port = 80  # Porta interna usada pelo NGINX (frontend)
  protocol = "tcp"
  [services.build]
    target = "frontend"  # Target para o frontend no Dockerfile

  [[services.ports]]
    handlers = ["http"]
    port = 8080  # Porta pública para o frontend (HTTP)

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443  # Porta pública para HTTPS