app = "sender-love"

# Configurações gerais de build
[build]

# Serviço do backend
[[services]]
  internal_port = 5001   # Porta interna do backend
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80  # Porta pública para o backend

  [services.build]
    dockerfile = "./backend/Dockerfile"  # Caminho para o Dockerfile do backend

# Serviço do frontend
[[services]]
  internal_port = 80   # Porta interna do frontend (NGINX)
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 8080  # Porta pública para o frontend

  [services.build]
    dockerfile = "./frontend/Dockerfile"  # Caminho para o Dockerfile do frontend