app = "senderlover"

# Configuração de build
[build]
  # Dockerfile para o backend
  dockerfile = "./backend/Dockerfile"
  
# Configuração do backend
[[services]]
  internal_port = 5001  # Porta interna do backend
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80  # Porta pública para o backend

# Configuração do frontend (separar build no nível global, não dentro do services)
[[services]]
  internal_port = 80  # Porta usada pelo NGINX (ou outro servidor de arquivos estáticos)
  protocol = "tcp"

  [build]
    dockerfile = "./frontend/Dockerfile"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 8080  # Porta pública para o frontend